---
- name: Create Users
  user:
    append: "{{ item.append | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    createhome: "{{ item.createhome | default(omit) }}"
    expires: "{{ item.expires | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    state: "{{ item.state | default(user_state) }}"
    system: "{{ item.system | default(user_system) }}"
    uid: "{{ item.uid | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
  with_items: "{{ user_list }}"